import { gColor } from "./gcolor";

export const gColorsDB = [
  new gColor('Shamrock', '#34ce7e'),
  new gColor('Emerald', '#5acf57'),
  new gColor('Laurel', '#328538'),
  new gColor('Green Pea', '#20723b'),
  new gColor('Elf Green', '#198663'),
  new gColor('Lake', '#257d93'),
  new gColor('Mariner', '#3876cc'),
  new gColor('Denim', '#116ec4'),
  new gColor('Cobalt Blue', '#0B4EAB'),
  new gColor('Royal Purple', '#64429c'),
  new gColor('Purple Heart', '#7d32b0'),
  new gColor('Blue Violet', '#994aed'),
  new gColor('Fuchsia', '#AF08AA'),
  new gColor('Razzmatazz', '#da0040'),
  new gColor('Alizarin', '#e72113'),
  new gColor('Fire Brick', '#a5213a'),
  new gColor('Persian Red', '#d73333'),
  new gColor('Blush', '#bf4a67'),
  new gColor('Desert', '#a0613d'),
  new gColor('Rust', '#c84d11'),
  new gColor('Sepia', '#704d16'),
  new gColor('Golden Brown', '#9e6710'),
  new gColor('Yukon Gold', '#8c741d'),
  new gColor('Burn Orange', '#f9722e'),
  new gColor('Sunglow', '#ffcf25'),
  new gColor('Gold Tips', '#e6b031'),
  new gColor('Milk Punch', '#f4e7c4'),
  new gColor('Silver', '#c0c0c0'),
  new gColor('Gravel', '#6e6e6e'),
  new gColor('Charcoal', '#444444'),
  new gColor('Cod Grey', '#1b1b1b'),
];

export const pixelColor = {
  Empty: new gColor('Empty', '#5a5a5a19'),
  RaisinBlack: new gColor('Raisin Black', '#27232a'),
  BrightGrey: new gColor('Bright Grey', "#efefef"),
  Periwinkle: new gColor('Periwinkle', '#c4d3ec'),
  LightSteelBlue: new gColor('Light Steel Blue', '#a8bde3'),
  BlueGrey: new gColor('Blue Grey', '#6c8fd0'),
  Pumpkin: new gColor('Pumpkin', "#f87b1b"),
  PhilippineBronze: new gColor('Philippine Bronze', "#652e03"),
  Claret: new gColor('Claret', "#7c122b"),
  DustStorm: new gColor('Dust Storm', "#dfc6bf"),
  DarkVanilla: new gColor('Dark Vanilla', "#d4b4ac"),
  Tuscany: new gColor('Tuscany', "#bf9d95"),
  Bone: new gColor('Bone', "#e7d4cf"),
  Platinum: new gColor('Platinum', "#efe5e2"),
  Ebb: new gColor('Ebb', "#e5d5d1"),
  Vanilla: new gColor('Vanilla', '#d0b3ab'),

  Shamrock: new gColor('Shamrock', '#34ce7e'),
  Emerald: new gColor('Emerald', '#5acf57'),
  Laurel: new gColor('Laurel', '#328538'),
  GreenPea: new gColor('Green Pea', '#20723b'),
  ElfGreen: new gColor('Elf Green', '#198663'),
  Lake: new gColor('Lake', '#257d93'),
  Mariner: new gColor('Mariner', '#3876cc'),
  Denim: new gColor('Denim', '#116ec4'),
  CobaltBlue: new gColor('Cobalt Blue', '#0B4EAB'),
  RoyalPurple: new gColor('Royal Purple', '#64429c'),
  PurpleHeart: new gColor('Purple Heart', '#7d32b0'),
  BlueViolet: new gColor('Blue Violet', '#994aed'),
  Fuchsia: new gColor('Fuchsia', '#AF08AA'),
  Razzmatazz: new gColor('Razzmatazz', '#da0040'),
  Alizarin: new gColor('Alizarin', '#e72113'),
  FireBrick: new gColor('Fire Brick', '#a5213a'),
  PersianRed: new gColor('Persian Red', '#d73333'),
  Blush: new gColor('Blush', '#bf4a67'),
  Desert: new gColor('Desert', '#a0613d'),
  Rust: new gColor('Rust', '#c84d11'),
  Sepia: new gColor('Sepia', '#704d16'),
  GoldenBrown: new gColor('Golden Brown', '#9e6710'),
  YukonGold: new gColor('Yukon Gold', '#8c741d'),
  BurnOrange: new gColor('Burn Orange', '#f9722e'),
  Sunglow: new gColor('Sunglow', '#ffcf25'),
  GoldTips: new gColor('Gold Tips', '#e6b031'),
  MilkPunch: new gColor('Milk Punch', '#f4e7c4'),
  Silver: new gColor('Silver', '#c0c0c0'),
  Gravel: new gColor('Gravel', '#6e6e6e'),
  Charcoal: new gColor('Charcoal', '#444444'),
  CodGrey: new gColor('Cod Grey', '#1b1b1b'),
};