export enum typeEnum {
  userFlow = 100,
  wireFrame,
  app,
  prototype,
  landingPage,
  motionGraphics,
  animation3D,
  document,
  module,
  socialMedia,
  graphicDesign,
  group,
  location,
}

export const type = {
  userFlow: "enum.projectsType.userFlow",
  wireFrame: "enum.projectsType.wireFrame",
  app: "enum.projectsType.app",
  prototype: "enum.projectsType.prototype",
  landingPage: "enum.projectsType.landingPage",
  motionGraphics: "enum.projectsType.motionGraphics",
  animation3D: "enum.projectsType.animation3D",
  document: "enum.projectsType.document",
  module: "enum.projectsType.module",
  socialMedia: "enum.projectsType.socialMedia",
  graphicDesign: "enum.projectsType.graphicDesign",
  group: "enum.projectsType.group",
  location: "enum.projectsType.location",
};